name: Continuous Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-build:
    runs-on: ubuntu-latest
    name: Build, lint and test
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.x
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm run build
      - name: Lint
        run: pnpm run prettier:check && pnpm run eslint:check
      - name: Lint Typescript
        run: pnpm run tsc

  # Leaving this as we may want to re-add tests and docs later
  required-checks-passed:
    name: All required checks passed
    runs-on: ubuntu-latest
    needs: [lint-build]
    steps:
      - run: exit 0